### PR TITLE
validate Terraform using CircleCI

### PR DESCRIPTION
**Pull request by afeld**
/cc https://github.com/GSA/DevSecOps-Infrastructure/pull/12

### CODE REVIEW

**Comment by Vermyndax** [comment]
@afeld was the build meant to fail? ;)

**Comment by afeld** [comment]
Waiting on https://github.com/GSA/DevSecOps-Infrastructure/pull/10 to determine how to proceed.

**Comment by afeld** [comment]
Ready!

**Comment by afeld** [comment]
Which part of the README needs to be updated?

**Comment by Vermyndax** [comment]
If we're going to remove variables from terraform.tfvars.example, we need to update the README to include instructions for including variables that aren't in the example file.

Excerpt:

Create the Terraform variables file.

cd terraform
cp terraform.tfvars.example terraform.tfvars
cp backend.tfvars.example backend.tfvars
Fill out terraform.tfvars. Mind the variable types and follow the noted rules.

**Pull request merged**
