### PR TITLE
harden the operating system of the Jenkins instance

### PR DESCRIPTION
**Pull request by afeld**

### CODE REVIEW

**Comment by afeld** [comment]
Hmm, Jenkins doesn't seem to be reachable within the instance when I tried this locally...will need to troubleshoot.

**Comment by Vermyndax** [comment]
There is a problem with this when I did it on the jenkins deployment. I had to switch the order of hardening to harden the instance after the jenkins installation in order to succeed. Still, occasionally, starting jenkins will fail. I couldn't reproduce it reliably.

**Comment by afeld** [comment]
@jeremy-gillikin and I found that Jenkins worked after restarting the instance - not sure why. Next thing to try is adding a reboot in between hardening and installing Jenkins.

**Comment by Vermyndax** [comment]
Yep, same experience I had too :(

**Comment by afeld** [comment]
Ready for review! Was able to redeploy Jenkins successfully.

**Pull request merged**
